spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/department_db
    username: newuser
    password: newuser
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/employees/**
          filters:
            - StripPrefix=2
        - id: department-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/departments/**
          filters:
            - StripPrefix=2