spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orgdatabase
    username: root
    password: root

# Logging
logging.level.org.springframework: INFO
management.endpoints.web.exposure.include: "*"
